# Generated by Django 4.2.11 on 2024-03-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(default='milanstvi', max_length=200),
            preserve_default=False,
        ),
    ]
